[0m20:22:43.705774 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000227A6D6D090>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000227A8DAADD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000227A8DAAF80>]}


============================== 20:22:43.725570 | daac96f0-6154-4b20-ba1c-ce10e53b56ed ==============================
[0m20:22:43.725570 [info ] [MainThread]: Running with dbt=1.10.2
[0m20:22:43.727580 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\csczy\\Documents\\public-data-etl\\dbt', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'introspect': 'True', 'invocation_command': 'dbt run', 'log_format': 'default', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m20:22:43.730112 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\csczy\Documents\public-data-etl\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m20:22:43.734406 [debug] [MainThread]: Command `dbt run` failed at 20:22:43.734406 after 0.99 seconds
[0m20:22:43.737916 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000227A6D6D090>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000227A8DAAC80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000227A8DAACB0>]}
[0m20:22:43.739440 [debug] [MainThread]: Flushing usage events
[0m20:22:44.422247 [debug] [MainThread]: An error was encountered while trying to flush usage events
